server:
  port: 8003
# 数据库设置
spring:
  application:
    name: zsxz-rcyh
  datasource:
    #url: jdbc:oracle:thin:@211.101.37.237:1521:orcl
    #username: zsxz
    #password: zsxz
    url: jdbc:oracle:thin:@192.168.10.230:1521:orcl
    username: c##zsxz
    password: zsxz
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,logging
      initial-size: 8
      min-idle: 3
      max-active: 100
      query-timeout: 6000
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 1800
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle:  true
      test-on-borrow: false
      test-on-return: false


mybatis:
  mapper-locations: classpath:/xml/*.xml
  type-aliases-package: com.hdsx.rcyh.etity
  config-location: classpath:mybatis-config.xml

#pagehelper分页插件配置
pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  offset-as-page-num: true
  row-bounds-with-count: true
  params: count=countSql
